### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by ericgonzalezs** [biocore-ntnu/snpflip#6]
Hi,

 I am using snpflip (downloaded today) as follows:

    snpflip -b Jonas_ordered.bim -f Zea_mays.AGPv3.22.dna.genome.fasta -o Jonas_snpflip

and I am getting the next output:

    Traceback (most recent call last):
    File "/usr/local/bin/snpflip", line 46, in <module>
    snp_table = create_snp_table(args["--bim-file"], args["--fasta-genome"])
    File "/usr/local/lib/python2.7/dist-packages/snp_flip/table.py", line 11, in create_snp_table
    reference_genome_data = get_reference_genome_data(bim_table, fa_file)
    File "/usr/local/lib/python2.7/dist-packages/snp_flip/reference_genome.py", line 18, in    get_reference_genome_data
    genome_dict = convert_fa_chromosome_names(pyfaidx_genome)
    File "/usr/local/lib/python2.7/dist-packages/snp_flip/reference_genome.py", line 76, in convert_fa_chromosome_names
    return {_convert_fa_name(k): fasta_dict[k] for k in fasta_dict.keys()
    File "/usr/local/lib/python2.7/dist-packages/snp_flip/reference_genome.py", line 77, in <dictcomp>
    if _is_valid_chromosome(k)}
    File "/usr/local/lib/python2.7/dist-packages/snp_flip/reference_genome.py", line 92, in _convert_fa_name
    result = bim_name.match(name).group("chr_symbol")
    AttributeError: 'NoneType' object has no attribute 'group'

Do you know what is happening? 
 
Thaks in advance,

Eric

**Comment by endrebak** [comment]
Thanks for reporting :)

It cannot find one of the chromosome names in the fasta or BIM file. Do the
names match in the two files and are all the chromosomes in the BIM file
present in the fasta?

Can you post the output of “cut -f 1 Jonas_ordered.bim | sort -u” and “cat
Zea_mays.AGPv3.22.dna.genome.fasta | grep '>'" please?

Endre

**Comment by ericgonzalezs** [comment]
Thank you very much!!

Yes, the problem was the scaffolds in the reference genome, what I did was to select the 10 chromosomes without scaffolds doing this:

    samtools faidx Zea_mays.AGPv3.22.dna.genome.fasta
    samtools faidx Zea_mays.AGPv3.22.dna.genome.fasta 1 2 3 4 5 6 7 8 9 10 > Zea_mays.AGPv3.22.dna.genome_sin_scaffolds.fasta

Now snpflip is working very well.  Thanks again,

Eric

**Comment by endrebak** [comment]
I am happy that it is now working. I wrote it before I had learnt how to code so it is not as robust as I'd like it to be.
